### PR TITLE
Removed reference to FootprintLayer

### PR DESCRIPTION
**Pull request by majcote**

### CODE REVIEW

**Comment by mikepurvis** [comment]
Confirm that the robot still navigates as expected with this change?

**Comment by majcote** [comment]
There doesn't seem to be any changes to the navigation performance

On Mon, Nov 30, 2015 at 4:31 PM, Mike Purvis notifications@github.com
wrote:

> Confirm that the robot still navigates as expected with this change?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jackal/jackal/pull/37#issuecomment-160767933.

## 

_Martin Cote_ | Technical Lead, Customer Success  | Clearpath Robotics, Inc.
1425 Strasburg Rd., Suite 2A, Kitchener, Ontario N2R 1H2 Canada
_T: \* 519-513-2416 x 858 | *E:_ mcote@clearpathrobotics.com
email@clearpathrobotics.com  | _W:_ www.clearpathrobotics.com

**Comment by davetcoleman** [comment]
I can confirm this needs to be removed - following the Jackal tutorials when I run:

```
roslaunch jackal_navigation odom_navigation_demo.launch
```

I get:

```
terminate called after throwing an instance of 'pluginlib::LibraryLoadException'
  what():  According to the loaded plugin descriptions the class costmap_2d::FootprintLayer with base class type costmap_2d::Layer does not exist. Declared types are  costmap_2d::InflationLayer costmap_2d::ObstacleLayer costmap_2d::StaticLayer costmap_2d::VoxelLayer
[move_base-1] process has died [pid 3523, exit code -6, cmd /opt/ros/indigo/lib/move_base/move_base odom:=odometry/filtered __name:=move_base __log:=/home/dave/.ros/log/346cdf5e-9d06-11e5-85db-d0509936edee/move_base-1.log].
log file: /home/dave/.ros/log/346cdf5e-9d06-11e5-85db-d0509936edee/move_base-1*.log
```

**Comment by mikepurvis** [comment]
Perfect, thanks all.

**Comment by davetcoleman** [comment]
I just confirmed this PR worked, btw

**Pull request merged**
