### PR TITLE
Added Sick LMS1XX URDF.

### PR DESCRIPTION
**Pull request by tonybaltovski**

### CODE REVIEW

**Comment by tonybaltovski** [comment]
clearpathrobotics/LMS1xx#17 was merged.

**Comment by mikepurvis** [comment]
This looks good; I assume you've verified that everything still looks good in simulation? eg, http://docs.ros.org/indigo/api/jackal_tutorials/html/navigation.html

**Comment by mikepurvis** [comment]
If so, merge away.

**Comment by tonybaltovski** [comment]
Applied via cherry-pick 5e107c99fb5037319b0fbf37f41f821b4417e7a6.

**Pull request closed without merging**
