### PR TITLE
ROS 2 Port of jackal_description

### PR DESCRIPTION
**Pull request by DLu**
* Adds `COLCON_IGNORE` for `jackal_control/jackal_msgs/jackal_navigation/jackal_tutorials`
 * Fairly standard port of `jackal_description` package files
 * Replaces `env_run` scripts with fancier launch arguments. Whether this is the right way to go with these scripts is open to debate. 
   * As a result, the scripts and `urdf/configs` folders are deleted. 
 * ~~Adds `display.launch.py` and a basic rviz config.~~
 * In the [second commit](https://github.com/jackal/jackal/commit/a694eed2ad20d0ba76950f714999731f393fe0d4), I comment out everything that depends on `lms1xx` and `pointgrey_camera_description`. Someone really should open up upstream issues to get ROS 2 ports of those.

### CODE REVIEW

**Comment by tonybaltovski** [comment]
Looks good and I agree with dropping the configs.  However, generally we put the rviz configs into `jackal_viz`.

**Comment by DLu** [comment]
* https://github.com/clearpathrobotics/LMS1xx/issues/67
 * https://github.com/ros-drivers/pointgrey_camera_driver/issues/211

**Comment by DLu** [comment]
Also, I have no idea where the configuration is to turn off melodic CI.

**Comment by tonybaltovski** [comment]
I made the branch for `jackal_desktop`.  We are likely to switch to https://github.com/SICKAG for the laser driver for ROS2 and no timeline for porting the pointgrey driver yet.

**Comment by tonybaltovski** [comment]
CI is here: https://github.com/jackal/jackal/blob/noetic-devel/.github/workflows/ci.yml

**Review by tonybaltovski — APPROVED** [review]

**Comment by tonybaltovski** [comment]
Thanks @DLu!

**Pull request merged**
