### PR TITLE
Accessories URDF Update

### PR DESCRIPTION
**Pull request by luis-camero**
Changes:
- use `xacro:property` to parse envvars to improve readability and extensibility
- added envvar to remove mounts on payloads that can have their mounts removed
- added OFFSET and RPY for NAVSAT
- updated NAVSAT stand to have input parameters `base_link` and `prefix` instead of just `mount`

### CODE REVIEW

**Comment by civerachb-cpr** [comment]
Are you still working on this, or is it ready for review?  If you're still making changes (or testing with the possibility of making further changes) can you please edit the title to include "WIP" until it's done?

**Comment by luis-camero** [comment]
I updated the title. I still do a few more tests and might make some changes as I work on the Noetic version. Once I'm done, I'll change the title and leave a comment.

**Comment by luis-camero** [comment]
I have tested that default behaviour is unchanged, and that the new environment variables behave as they should. 

When removing the towers/mounts the default position may no longer be [0, 0, 0]. Therefore, the default position (i.e. if the envvar has not been set) have been changed when the mount is disabled. 

 Should I add an intermediate link so that the unmounted default position is [0, 0, 0]?

**Comment by luis-camero** [comment]
Default positions are all zero. 

Done, no longer WIP.

**Review by tonybaltovski — APPROVED** [review]

**Pull request merged**
