### PR TITLE
Increased inflation radius to account for uneven walls in jackal_world

### PR DESCRIPTION
**Pull request by majcote**

### CODE REVIEW

**Comment by ibaranov-cp** [comment]
Looks reasonable to me.

**Comment by mikepurvis** [comment]
This means the total diameter is almost a metre— it could have difficulty navigating through a standard doorway like this. I get the motivation, but I'm wondering if a smaller increase would do as well (maybe we should also be considering a change to the sim world so that this issue is minimized or eliminated on that end?

**Comment by majcote** [comment]
Sure, I can test a smaller increase. I also agree changing the sim world be
the better solution.

On Thu, Nov 5, 2015 at 2:15 PM, Mike Purvis notifications@github.com
wrote:

> This means the total diameter is almost a metre— it could have difficulty
> navigating through a standard doorway like this. I get the motivation, but
> I'm wondering if a smaller increase would do as well (maybe we should also
> be considering a change to the sim world so that this issue is minimized or
> eliminated on that end?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jackal/jackal/pull/36#issuecomment-154158927.

## 

_Martin Cote_ | Technical Lead, Customer Success  | Clearpath Robotics, Inc.
1425 Strasburg Rd., Suite 2A, Kitchener, Ontario N2R 1H2 Canada
_T: \* 519-513-2416 x 858 | *E:_ mcote@clearpathrobotics.com
email@clearpathrobotics.com  | _W:_ www.clearpathrobotics.com

**Comment by majcote** [comment]
0.3 seems to be sufficient for the current jackal_world

**Comment by mikepurvis** [comment]
I'm comfortable with 0.3, thanks.

**Pull request merged**
