### PR TITLE
Allow for jackal urdf to be included from other models

### PR DESCRIPTION
**Pull request by ghost**
Make urdf refer explicitly to jackal_description, rather than relying on current working directory being correct, for easier external includes.

Makes a completely seperate urdf for a UR3 integration much simpler. See https://gitlab.com/akalmbach/jackal_manipulator

@tonybaltovski, @mcoteCPR  re: Zendesk 4401

### CODE REVIEW

**Comment by ghost** [comment]
@tonybaltovski Can we merge this? It makes the [URDF for Jackal+Arm](
https://gitlab.com/akalmbach/jackal_manipulator/blob/master/jackal_manipulator_description/urdf/jackal.urdf.xacro) as simple as 4 lines, rather than duplicating the entire Jackal URDF.

**Comment by tonybaltovski** [comment]
@akalmbach I was imagining a different way to perform like the way I did it here: https://github.com/tonybaltovski/ridgeback_ur5.  My initial concern with this is breaks existing setups that do use  `JACKAL_URDF_EXTRAS` since it is disabled by default.  Additionally, it seems like there would a lot of repetition between the launch files.  Is there a reason doing it this way in particular?

**Comment by ghost** [comment]
@tonybaltovski This is very similar to what you did (that part is in the [jackal_manipulator repo](https://gitlab.com/akalmbach/jackal_manipulator/blob/master/jackal_manipulator_description/urdf/jackal.urdf.xacro)). These changes are to make the jackal urdf refer explicitly to paths under jackal description, because `.` resolves to the *calling* urdf when parsing a macro. So this avoids the need to maintain a separate copy of the main jackal urdf or to keep anything depending on the arm in jackal_description itself.

The change involving JACKAL_URDF_EXTRAS is to avoid using the empty.urdf file. If there are extras they should resolve in the exact same way, if there are no extras, nothing is included instead of the stub file. If you prefer I could change it to:
`<xacro:include filename="$(find jackal_description)/urdf/$(optenv JACKAL_URDF_EXTRAS empty.urdf)" />`
which would avoid the need to add `--inorder` to the launchfile

However the thing we really want:
`<xacro:include filename="$(optenv JACKAL_URDF_EXTRAS $(find jackal_description)/urdf/empty.urdf)" />`
is not valid URDF

**Comment by mikepurvis** [comment]
Clever. I dig it. :+1:

**Pull request merged**
